# getting base image ubuntu
FROM ubuntu

MAINTAINER satish <satish368419@gmail.com>

RUN apt-get update

CMD ["echo", "Hello world....! from my first docker image"]

# copy war file on to container 
COPY ./webapp.war /usr/local/tomcat/webapps


